import React, { useState } from "react";
import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'

import Button from '@mui/material/Button';
import Input from '@mui/material/Input';
import { Router } from "next/router";

import CityCard from './CityCard.js'

const ariaLabel = { 'aria-label': 'description' };

const URL = `http://api.weatherapi.com/v1/current.json?key=${API_KEY}&q=`

class App extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			city: "",
			isClicked: false,
			temperature: 0,
		}
		this.onButtonPress = this.onButtonPress.bind(this)
	}

	onButtonPress(event) {
		event.preventDefault();
		this.fetchComments()

		this.setState({ isClicked: true })
	}

	fetchComments = async () => {
		const res = await fetch(`${URL}${this.state.city}`)
		const data = await res.json()
		this.setState({temperature: data.current.temp_f})
	}
	render() {

		return (
			<div className={styles.container}>
				<Head>
					<title>SIGO</title>
					<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				</Head>
				{/* Main Styling */}
				<main className={styles.main}>
					<h1 className={styles.title}>
						Welcome to <a href="https://github.com/bryanmontalvan/SIGO">SIGO</a>
					</h1>
					<p className={styles.description}>
						A tool to know when to head out
					</p>
					<div className={styles.searchField}>
						<Input
							placeholder="Boston"
							inputProps={ariaLabel}
							onChange={(e) => {
								this.setState({ city: e.target.value });
							}}
							/>
						<Button variant="contained" color="primary" onClick={this.onButtonPress}>Search</Button>
					</div>
					{/* City Card */}
					<h3>The city you entered is:  </h3>
					{this.state.isClicked ? <CityCard cityName={this.state.city} temp={this.state.temperature}/> : null}
				</main>
				<footer className={styles.footer}>
					<a
						href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						target="_blank"
						rel="noopener noreferrer"
					>
						Powered by{' '}
						<span className={styles.logo}>
							<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
						</span>
					</a>
				</footer>
			</div>
		)
	}
}

export default App;